<?php

/**
 * Base static class for performing query and update operations on the 'cadastro' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Qua 09 Set 2009 20:50:29 BRT
 *
 * @package    lib.model.om
 */
abstract class BaseCadastroPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'cadastro';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.Cadastro';

	/** The total number of columns. */
	const NUM_COLUMNS = 21;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the ID field */
	const ID = 'cadastro.ID';

	/** the column name for the NOME field */
	const NOME = 'cadastro.NOME';

	/** the column name for the CPF field */
	const CPF = 'cadastro.CPF';

	/** the column name for the EMAIL_PESSOAL field */
	const EMAIL_PESSOAL = 'cadastro.EMAIL_PESSOAL';

	/** the column name for the EMAIL_PROFISSIONAL field */
	const EMAIL_PROFISSIONAL = 'cadastro.EMAIL_PROFISSIONAL';

	/** the column name for the MUNICIPIO field */
	const MUNICIPIO = 'cadastro.MUNICIPIO';

	/** the column name for the TELEFONE field */
	const TELEFONE = 'cadastro.TELEFONE';

	/** the column name for the VALIDADO field */
	const VALIDADO = 'cadastro.VALIDADO';

	/** the column name for the LOGRADOURO field */
	const LOGRADOURO = 'cadastro.LOGRADOURO';

	/** the column name for the BAIRRO field */
	const BAIRRO = 'cadastro.BAIRRO';

	/** the column name for the NUMERO field */
	const NUMERO = 'cadastro.NUMERO';

	/** the column name for the COMPLEMENTO field */
	const COMPLEMENTO = 'cadastro.COMPLEMENTO';

	/** the column name for the ESTADO field */
	const ESTADO = 'cadastro.ESTADO';

	/** the column name for the CEP field */
	const CEP = 'cadastro.CEP';

	/** the column name for the CREATED_AT field */
	const CREATED_AT = 'cadastro.CREATED_AT';

	/** the column name for the CELULAR field */
	const CELULAR = 'cadastro.CELULAR';

	/** the column name for the INSTITUICAO_TRABALHO field */
	const INSTITUICAO_TRABALHO = 'cadastro.INSTITUICAO_TRABALHO';

	/** the column name for the PROFISSAO field */
	const PROFISSAO = 'cadastro.PROFISSAO';

	/** the column name for the OPCAO_1_OFICINA field */
	const OPCAO_1_OFICINA = 'cadastro.OPCAO_1_OFICINA';

	/** the column name for the OPCAO_2_OFICINA field */
	const OPCAO_2_OFICINA = 'cadastro.OPCAO_2_OFICINA';

	/** the column name for the SEXO field */
	const SEXO = 'cadastro.SEXO';

	/**
	 * An identiy map to hold any loaded instances of Cadastro objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array Cadastro[]
	 */
	public static $instances = array();

	/**
	 * The MapBuilder instance for this peer.
	 * @var        MapBuilder
	 */
	private static $mapBuilder = null;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Id', 'Nome', 'Cpf', 'EmailPessoal', 'EmailProfissional', 'Municipio', 'Telefone', 'Validado', 'Logradouro', 'Bairro', 'Numero', 'Complemento', 'Estado', 'Cep', 'CreatedAt', 'Celular', 'InstituicaoTrabalho', 'Profissao', 'Opcao1Oficina', 'Opcao2Oficina', 'Sexo', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'nome', 'cpf', 'emailPessoal', 'emailProfissional', 'municipio', 'telefone', 'validado', 'logradouro', 'bairro', 'numero', 'complemento', 'estado', 'cep', 'createdAt', 'celular', 'instituicaoTrabalho', 'profissao', 'opcao1Oficina', 'opcao2Oficina', 'sexo', ),
		BasePeer::TYPE_COLNAME => array (self::ID, self::NOME, self::CPF, self::EMAIL_PESSOAL, self::EMAIL_PROFISSIONAL, self::MUNICIPIO, self::TELEFONE, self::VALIDADO, self::LOGRADOURO, self::BAIRRO, self::NUMERO, self::COMPLEMENTO, self::ESTADO, self::CEP, self::CREATED_AT, self::CELULAR, self::INSTITUICAO_TRABALHO, self::PROFISSAO, self::OPCAO_1_OFICINA, self::OPCAO_2_OFICINA, self::SEXO, ),
		BasePeer::TYPE_FIELDNAME => array ('id', 'nome', 'cpf', 'email_pessoal', 'email_profissional', 'municipio', 'telefone', 'validado', 'logradouro', 'bairro', 'numero', 'complemento', 'estado', 'cep', 'created_at', 'celular', 'instituicao_trabalho', 'profissao', 'opcao_1_oficina', 'opcao_2_oficina', 'sexo', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'Nome' => 1, 'Cpf' => 2, 'EmailPessoal' => 3, 'EmailProfissional' => 4, 'Municipio' => 5, 'Telefone' => 6, 'Validado' => 7, 'Logradouro' => 8, 'Bairro' => 9, 'Numero' => 10, 'Complemento' => 11, 'Estado' => 12, 'Cep' => 13, 'CreatedAt' => 14, 'Celular' => 15, 'InstituicaoTrabalho' => 16, 'Profissao' => 17, 'Opcao1Oficina' => 18, 'Opcao2Oficina' => 19, 'Sexo' => 20, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'nome' => 1, 'cpf' => 2, 'emailPessoal' => 3, 'emailProfissional' => 4, 'municipio' => 5, 'telefone' => 6, 'validado' => 7, 'logradouro' => 8, 'bairro' => 9, 'numero' => 10, 'complemento' => 11, 'estado' => 12, 'cep' => 13, 'createdAt' => 14, 'celular' => 15, 'instituicaoTrabalho' => 16, 'profissao' => 17, 'opcao1Oficina' => 18, 'opcao2Oficina' => 19, 'sexo' => 20, ),
		BasePeer::TYPE_COLNAME => array (self::ID => 0, self::NOME => 1, self::CPF => 2, self::EMAIL_PESSOAL => 3, self::EMAIL_PROFISSIONAL => 4, self::MUNICIPIO => 5, self::TELEFONE => 6, self::VALIDADO => 7, self::LOGRADOURO => 8, self::BAIRRO => 9, self::NUMERO => 10, self::COMPLEMENTO => 11, self::ESTADO => 12, self::CEP => 13, self::CREATED_AT => 14, self::CELULAR => 15, self::INSTITUICAO_TRABALHO => 16, self::PROFISSAO => 17, self::OPCAO_1_OFICINA => 18, self::OPCAO_2_OFICINA => 19, self::SEXO => 20, ),
		BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'nome' => 1, 'cpf' => 2, 'email_pessoal' => 3, 'email_profissional' => 4, 'municipio' => 5, 'telefone' => 6, 'validado' => 7, 'logradouro' => 8, 'bairro' => 9, 'numero' => 10, 'complemento' => 11, 'estado' => 12, 'cep' => 13, 'created_at' => 14, 'celular' => 15, 'instituicao_trabalho' => 16, 'profissao' => 17, 'opcao_1_oficina' => 18, 'opcao_2_oficina' => 19, 'sexo' => 20, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, )
	);

	/**
	 * Get a (singleton) instance of the MapBuilder for this peer class.
	 * @return     MapBuilder The map builder for this peer
	 */
	public static function getMapBuilder()
	{
		if (self::$mapBuilder === null) {
			self::$mapBuilder = new CadastroMapBuilder();
		}
		return self::$mapBuilder;
	}
	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. CadastroPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(CadastroPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{

		$criteria->addSelectColumn(CadastroPeer::ID);

		$criteria->addSelectColumn(CadastroPeer::NOME);

		$criteria->addSelectColumn(CadastroPeer::CPF);

		$criteria->addSelectColumn(CadastroPeer::EMAIL_PESSOAL);

		$criteria->addSelectColumn(CadastroPeer::EMAIL_PROFISSIONAL);

		$criteria->addSelectColumn(CadastroPeer::MUNICIPIO);

		$criteria->addSelectColumn(CadastroPeer::TELEFONE);

		$criteria->addSelectColumn(CadastroPeer::VALIDADO);

		$criteria->addSelectColumn(CadastroPeer::LOGRADOURO);

		$criteria->addSelectColumn(CadastroPeer::BAIRRO);

		$criteria->addSelectColumn(CadastroPeer::NUMERO);

		$criteria->addSelectColumn(CadastroPeer::COMPLEMENTO);

		$criteria->addSelectColumn(CadastroPeer::ESTADO);

		$criteria->addSelectColumn(CadastroPeer::CEP);

		$criteria->addSelectColumn(CadastroPeer::CREATED_AT);

		$criteria->addSelectColumn(CadastroPeer::CELULAR);

		$criteria->addSelectColumn(CadastroPeer::INSTITUICAO_TRABALHO);

		$criteria->addSelectColumn(CadastroPeer::PROFISSAO);

		$criteria->addSelectColumn(CadastroPeer::OPCAO_1_OFICINA);

		$criteria->addSelectColumn(CadastroPeer::OPCAO_2_OFICINA);

		$criteria->addSelectColumn(CadastroPeer::SEXO);

	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(CadastroPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			CadastroPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(CadastroPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}


    foreach (sfMixer::getCallables('BaseCadastroPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseCadastroPeer', $criteria, $con);
    }


		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     Cadastro
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = CadastroPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return CadastroPeer::populateObjects(CadastroPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseCadastroPeer:doSelectStmt:doSelectStmt') as $callable)
    {
      call_user_func($callable, 'BaseCadastroPeer', $criteria, $con);
    }


		if ($con === null) {
			$con = Propel::getConnection(CadastroPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			CadastroPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      Cadastro $value A Cadastro object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(Cadastro $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A Cadastro object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof Cadastro) {
				$key = (string) $value->getId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or Cadastro object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     Cadastro Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol + 0] === null) {
			return null;
		}
		return (string) $row[$startcol + 0];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = CadastroPeer::getOMClass();
		$cls = substr('.'.$cls, strrpos('.'.$cls, '.') + 1);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = CadastroPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = CadastroPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
		
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				CadastroPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}

  static public function getUniqueColumnNames()
  {
    return array(array('cpf'), array('email_profissional'));
  }
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * This uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass()
	{
		return CadastroPeer::CLASS_DEFAULT;
	}

	/**
	 * Method perform an INSERT on the database, given a Cadastro or Criteria object.
	 *
	 * @param      mixed $values Criteria or Cadastro object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseCadastroPeer:doInsert:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseCadastroPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(CadastroPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from Cadastro object
		}

		if ($criteria->containsKey(CadastroPeer::ID) && $criteria->keyContainsValue(CadastroPeer::ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.CadastroPeer::ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

		
    foreach (sfMixer::getCallables('BaseCadastroPeer:doInsert:post') as $callable)
    {
      call_user_func($callable, 'BaseCadastroPeer', $values, $con, $pk);
    }

    return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a Cadastro or Criteria object.
	 *
	 * @param      mixed $values Criteria or Cadastro object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseCadastroPeer:doUpdate:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseCadastroPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(CadastroPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(CadastroPeer::ID);
			$selectCriteria->add(CadastroPeer::ID, $criteria->remove(CadastroPeer::ID), $comparison);

		} else { // $values is Cadastro object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);
	

    foreach (sfMixer::getCallables('BaseCadastroPeer:doUpdate:post') as $callable)
    {
      call_user_func($callable, 'BaseCadastroPeer', $values, $con, $ret);
    }

    return $ret;
  }

	/**
	 * Method to DELETE all rows from the cadastro table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(CadastroPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(CadastroPeer::TABLE_NAME, $con);
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a Cadastro or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or Cadastro object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(CadastroPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			CadastroPeer::clearInstancePool();

			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof Cadastro) {
			// invalidate the cache for this single object
			CadastroPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else {
			// it must be the primary key



			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(CadastroPeer::ID, (array) $values, Criteria::IN);

			foreach ((array) $values as $singleval) {
				// we can invalidate the cache for this single object
				CadastroPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);

			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given Cadastro object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      Cadastro $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(Cadastro $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(CadastroPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(CadastroPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		$res =  BasePeer::doValidate(CadastroPeer::DATABASE_NAME, CadastroPeer::TABLE_NAME, $columns);
    if ($res !== true) {
        $request = sfContext::getInstance()->getRequest();
        foreach ($res as $failed) {
            $col = CadastroPeer::translateFieldname($failed->getColumn(), BasePeer::TYPE_COLNAME, BasePeer::TYPE_PHPNAME);
        }
    }

    return $res;
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     Cadastro
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = CadastroPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(CadastroPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(CadastroPeer::DATABASE_NAME);
		$criteria->add(CadastroPeer::ID, $pk);

		$v = CadastroPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(CadastroPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(CadastroPeer::DATABASE_NAME);
			$criteria->add(CadastroPeer::ID, $pks, Criteria::IN);
			$objs = CadastroPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

} // BaseCadastroPeer

// This is the static code needed to register the MapBuilder for this table with the main Propel class.
//
// NOTE: This static code cannot call methods on the CadastroPeer class, because it is not defined yet.
// If you need to use overridden methods, you can add this code to the bottom of the CadastroPeer class:
//
// Propel::getDatabaseMap(CadastroPeer::DATABASE_NAME)->addTableBuilder(CadastroPeer::TABLE_NAME, CadastroPeer::getMapBuilder());
//
// Doing so will effectively overwrite the registration below.

Propel::getDatabaseMap(BaseCadastroPeer::DATABASE_NAME)->addTableBuilder(BaseCadastroPeer::TABLE_NAME, BaseCadastroPeer::getMapBuilder());

