<?php


/**
 * This class adds structure of 'cadastro' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Qua 09 Set 2009 20:50:29 BRT
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class CadastroMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.CadastroMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(CadastroPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(CadastroPeer::TABLE_NAME);
		$tMap->setPhpName('Cadastro');
		$tMap->setClassname('Cadastro');

		$tMap->setUseIdGenerator(true);

		$tMap->setPrimaryKeyMethodInfo('cadastro_id_seq');

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addColumn('NOME', 'Nome', 'VARCHAR', true, 255);

		$tMap->addColumn('CPF', 'Cpf', 'VARCHAR', true, 15);

		$tMap->addColumn('EMAIL_PESSOAL', 'EmailPessoal', 'VARCHAR', false, 255);

		$tMap->addColumn('EMAIL_PROFISSIONAL', 'EmailProfissional', 'VARCHAR', true, 255);

		$tMap->addColumn('MUNICIPIO', 'Municipio', 'VARCHAR', true, 255);

		$tMap->addColumn('TELEFONE', 'Telefone', 'VARCHAR', true, 15);

		$tMap->addColumn('VALIDADO', 'Validado', 'BOOLEAN', true, null);

		$tMap->addColumn('LOGRADOURO', 'Logradouro', 'VARCHAR', true, 255);

		$tMap->addColumn('BAIRRO', 'Bairro', 'VARCHAR', true, 255);

		$tMap->addColumn('NUMERO', 'Numero', 'INTEGER', true, null);

		$tMap->addColumn('COMPLEMENTO', 'Complemento', 'VARCHAR', false, 255);

		$tMap->addColumn('ESTADO', 'Estado', 'VARCHAR', true, 2);

		$tMap->addColumn('CEP', 'Cep', 'VARCHAR', true, 9);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('CELULAR', 'Celular', 'VARCHAR', false, 255);

		$tMap->addColumn('INSTITUICAO_TRABALHO', 'InstituicaoTrabalho', 'VARCHAR', false, 255);

		$tMap->addColumn('PROFISSAO', 'Profissao', 'VARCHAR', true, 255);

		$tMap->addColumn('OPCAO_1_OFICINA', 'Opcao1Oficina', 'INTEGER', false, null);

		$tMap->addColumn('OPCAO_2_OFICINA', 'Opcao2Oficina', 'INTEGER', false, null);

		$tMap->addColumn('SEXO', 'Sexo', 'BOOLEAN', false, null);

	} // doBuild()

} // CadastroMapBuilder
