<?php


/**
 * This class adds structure of 'trabalho' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Wed May 20 10:52:52 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class TrabalhoMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.TrabalhoMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(TrabalhoPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(TrabalhoPeer::TABLE_NAME);
		$tMap->setPhpName('Trabalho');
		$tMap->setClassname('Trabalho');

		$tMap->setUseIdGenerator(true);

		$tMap->setPrimaryKeyMethodInfo('trabalho_id_seq');

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addColumn('PRIMEIRO_NOME', 'PrimeiroNome', 'VARCHAR', true, 255);

		$tMap->addColumn('NOME_MEIO', 'NomeMeio', 'VARCHAR', false, 255);

		$tMap->addColumn('SOBRENOME', 'Sobrenome', 'VARCHAR', true, 255);

		$tMap->addColumn('EMAIL', 'Email', 'VARCHAR', true, 255);

		$tMap->addColumn('INSTITUICAO', 'Instituicao', 'VARCHAR', false, 255);

		$tMap->addColumn('RESUMO_BIOGRAFIA', 'ResumoBiografia', 'LONGVARCHAR', true, null);

		$tMap->addForeignKey('EIXO_TEMATICO_ID', 'EixoTematicoId', 'INTEGER', 'eixo_tematico', 'ID', true, null);

		$tMap->addColumn('ARQUIVO', 'Arquivo', 'VARCHAR', true, 255);

		$tMap->addColumn('APROVADO', 'Aprovado', 'BOOLEAN', false, null);

		$tMap->addColumn('TITULO', 'Titulo', 'VARCHAR', true, 255);

		$tMap->addColumn('CONTATO_CORRESPONDENCIA', 'ContatoCorrespondencia', 'BOOLEAN', true, null);

	} // doBuild()

} // TrabalhoMapBuilder
