<?php


/**
 * This class adds structure of 'trabalhos_co_autor' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Fri May  8 15:32:42 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class TrabalhosCoAutorMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.TrabalhosCoAutorMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(TrabalhosCoAutorPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(TrabalhosCoAutorPeer::TABLE_NAME);
		$tMap->setPhpName('TrabalhosCoAutor');
		$tMap->setClassname('TrabalhosCoAutor');

		$tMap->setUseIdGenerator(false);

		$tMap->addForeignPrimaryKey('TRABALHO_ID', 'TrabalhoId', 'INTEGER' , 'trabalho', 'ID', true, null);

		$tMap->addForeignPrimaryKey('CO_AUTOR_ID', 'CoAutorId', 'INTEGER' , 'co_autor', 'ID', true, null);

	} // doBuild()

} // TrabalhosCoAutorMapBuilder
